ethereum-optimism/supersim

anvil/anvil.go
supersim.go

worked on this with @jakim929.
Spins up a single vanilla anvil instance. Gives us a base to creating more than one instance

single anvil instance

---

contracts/script/Deploy.s.sol

Just adds a basic deploy script we can use for deploying to anvil and testnets
Tracker: https://github.com/ethereum-optimism/supersim/issues/3

Adds basic deploy script for game

---

opsimulator/opsimulator.go

Recently pulled the latest version of supersim and was running into cors issues again. We recently updated how the reverse proxy is created and how we forward the requests. The issue is we aren't adding the cors header back to the response. The last issue was related to not handling options request.
This PR adds a top level cors middleware that handles options requests and applies the cors headers to all responses so we can avoid breaking this again in the future.

Adds Top Level CORS MIddleware

---

orchestrator/fork.go
orchestrator/orchestrator.go
supersim.go
supersim_test.go

From the walkthrough.
- use the right rpc url
- check to make sure chain id matches
- make l2opsims a private member of the orchestrator
- dont stop close on first error
Some more fixes after fixing some abstractions
Closes #105

fixes: orchestrator

---

anvil/anvil.go
config/chain.go
opsimulator/deposits.go
opsimulator/opsimulator.go
orchestrator/fork.go
orchestrator/orchestrator.go
supersim.go
supersim_test.go
testutils/mockchain.go

Dup of #111 that accidentally got merged into this branch

fixes: anvil & chain abstraction

---

opsimulator/opsimulator.go
orchestrator/orchestrator.go

- uses the L2ToL2MessageStoreManager to store and log cross domain messages
- subscribes to all events from the crosschainmessenger

feat(opsim): log L2CDM events

---

bindings/parsedabi.go
bindings/simplestorage.go
contracts/src/SimpleStorage.sol
supersim_test.go

- adds bindings to deploy / interact with SimpleStorage contract
- checks that autorelay correctly sets the value on the destination chain

test(l2tol2msg): adds SimpleStorage to test autorelay

---

opsimulator/opsimulator.go

Noticed startup time was very slow these days. This slows down iteration and tests.
- Most of the startup time was waiting for opsim to get ready
- Mostly spent waiting for the tx receipt on the tx to set the dependencySet
- Since we run anvil in automine mode in the beginning, the tx should land very fast but still asynchronously (with a small delay AFTER the rpc call returns, since anvil internally has a job queue for mining)
- updated logic for checking tx to check at faster tick intervals since we assume the tx will land. The default bind.WaitMined checks every second (leading to it taking 2 seconds)
Before
After

fix(opsim): improve startup time

---

README.md

This PR adds a section explaining the "why" of supersim, pointing to our north star of making superchain development smoother for app devs.

Add why supersim section

---

README.md
docs/book.toml
docs/src/SUMMARY.md
docs/src/getting-started/first-steps.md
docs/src/guides/interop/calling-destination-contract.md
docs/src/guides/interop/interop-identifiers.md
docs/src/guides/interop/manually-relaying-interop-messages-cast.md
docs/src/guides/interop/relay-using-viem-full-code.md
docs/src/guides/interop/relay-using-viem.md
docs/src/guides/interop/writing-contract-using-l2cdm.md

Adds two guides
- manually relaying interop tx using cast
- using viem actions to relay interop tx

docs: guide to manually relay interop tx using cast / viem

---

README.md
docs/src/getting-started/installation.md

```sh
brew tap ethereum-optimism/tap
brew install supersim
```
also update README so users can get to Getting Started faster

chore: update README and docs to include brew install

---

.github/ISSUE_TEMPLATE/bug_report.md

adds section for foundry version
closes https://github.com/ethereum-optimism/supersim/issues/158
Later on we might want to create a yml form. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

chore: update bug report issue template

---

cmd/main.go

alert user to prevent issues like https://github.com/ethereum-optimism/supersim/issues/155

chore: update min anvil version

---

anvil/anvil.go

Part of https://github.com/ethereum-optimism/supersim/issues/183

feat: set anvil `--max-persisted-states` flag

---

.github/workflows/main.yml

**Tests**
**Additional context**
**Metadata**

Removes prt

---

.github/workflows/main.yml

Updates our unit tests to use public endpoints instead of private ones

update unit tests to read from vars instead of secrets

---

README.md

moved after getting started before docker run

---

contracts/src/SuperchainETHWrapper.sol
contracts/src/tictactoe/TicTacToe.sol
docs/src/guides/interop/cross-chain-contract-via-l2cdm.md
docs/src/guides/interop/manually-relaying-interop-messages-cast.md

Fix typos in the docs and in the TicTacToe contract

fix: typos

---

README.md

Added an "awesome supersim" section at the bottom of the readme to include links to things build with or on supersim.
link to [preview](https://github.com/ethereum-optimism/supersim/pull/248/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

Added awesome supersim section at the bottom of the readme

---

admin/admin_test.go
opsimulator/opsimulator.go

updated L2NativeSuperchainERC20 and SuperchainWETH to use similar logging
**Metadata**
https://github.com/ethereum-optimism/supersim/issues/144

💅 refactor L2NativeSuperchainERC20 and SuperchainWETH logging

---

anvil/anvil.go

Closes https://github.com/ethereum-optimism/supersim/issues/118

feat: use `pending` tag for `debug_traceCall`

---

interop/relayer.go

Fixed an issue where the auto-relayer would stop processing messages when a relay attempt failed. The bug had two root causes:
1. Using `defer` for mutex unlocking, which prevented the mutex from being released until the goroutine terminated
2. Returning errors from `relayMessageWithRetry` which would cause the subscription goroutine to exit prematurely
- Removed `defer r.checkForDependentMsgHashMutex.RUnlock()` in favor of explicit unlocking after message processing
- Modified error handling in `relayMessageWithRetry` to log errors but continue processing instead of returning them

fix: bug in relayer that causes it to hang infinitely on failed relays

---

cmd/main.go
mise.toml
readme_test.go

to include https://github.com/foundry-rs/foundry/pull/9883

feat: bump min required anvil

---

interop/relayer.go

Closes https://github.com/ethereum-optimism/supersim/issues/335
This PR adds additional logging for when the auto-relayer fails to relay cross domain message through L2toL2CDM.relayMessage. When this fails, it will debug trace call the failure and print out the trace to the terminal along with the message identifier and payload so that devs can more easily debug why a failure occured.
Here is an example of what prints to the terminal:
```ERROR[02-14|11:07:02.718] failed to relay message                  err="execution reverted: custom error 0xeda86850" attempt=1 maxRetries=1
debug trace result of failed relay:
{
"type": "CALL",
"from": "0xa0ee7a142d267c1f36714e4a8f75612f20a79720",
"to": "0x4200000000000000000000000000000000000023",
"value": "0x0",
"gas": "0x1c96568",
"gasUsed": "0xf99e", …
```

feat: print call trace when message auto-relays fail

---

.circleci/config.yml
docs/src/chain-environment/contracts/README.md

This PR changes a broken link to use the relative path so it doesn't break in the docs.

Fix: broken link

---

anvil/anvil.go
config/chain.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
supersim_test.go
testutils/mockchain.go

Closes https://github.com/ethereum-optimism/supersim/issues/374

feat: support websocket connections to supersim l2 chains
