.github/workflows/contracts-tests.yml
.gitmodules
contracts/.github/workflows/test.yml
contracts/.gitignore
contracts/README.md
contracts/foundry.toml
contracts/script/Counter.s.sol
contracts/src/Counter.sol
contracts/test/Counter.t.sol

* Adds a new top level directory called `contracts` this inits a fresh foundry project with no changes. The default project comes with some counter contracts I'll remove those when i add the tic tac toe contracts
* Adds github actions to build and run unit tests for contracts when a PR is open against `main`, and when it gets merged into `main`

Init Foundry

---

.gitignore
.vscode/settings.json

- adds default golang .gitignore from https://github.com/github/gitignore/blob/main/Go.gitignore
- adds formatter config for vscode

chore: add .gitignore

---

cmd/main.go
supersim.go

result from team session
supersim now spins up multiple chains (1 L1 chain and multiple L2 chains) based on the config

feat: spin up multiple chains

---

anvil/anvil.go
supersim.go
supersim_test.go
utils/rpc.go

Part of https://github.com/ethereum-optimism/supersim/issues/15
Realized that the genesis files need to be embedded into the go executable. This PR embeds the genesis json files, writes them to a temporary file, and then passes the temp file into the anvil instances on startup.

feat(genesis-state): embed genesis state files in go binary

---

.github/actions/setup/action.yml
.github/workflows/main.yml
Justfile
scripts/local-dev-setup.sh

* Adds `Justfile` along with some commands
* `build-contracts` builds the forge project
* `build-go` builds supersim
* `test-contracts` runs the forge unit tests
* `test-go` runs the go unit tests
* `start` starts supersim
* Adds `scripts/local-dev-setup.sh` this is the start of a script we can use to make it easy for devs to setup their local dev environment
* Updates our github actions to install `just` and updates the commands in the actions to use the `Justfile`
Once we merge this in will follow on with some README updates!

Adds Justfile

---

.github/workflows/main.yml
Justfile
anvil/anvil.go
scripts/local-dev-setup.sh
supersim_test.go
utils/rpc.go

This PR adds [golangci-lint](https://golangci-lint.run/), this is what we're using in the monorepo.
* Updates `local-dev-setup.sh` to include an install step for the linter to be used locally
* Updates `Justfile` to include a new command called `lint-go`. The command used here is shamelessly copied from the monorepo. I figure it's best to start with the same linting rules and adjust from here.
* Updates CI to run the linter
* Fixes lint issues

Adds Go Linter

---

op-simulator/op_simulator.go
supersim.go
supersim_test.go

Closes https://github.com/ethereum-optimism/supersim/issues/16
This PR makes the following changes:
- creates `op_simulator` package
- sets up `op_simulator` for each chain as a ReverseProxy that intercepts all rpc requests and forwards them to the underlying anvil node for that chain
- coordinates starting and stopping of all `op_simulator` and `anvil` instances using the `supersim` package

feat: create op-simulator as basic proxy

---

.vscode/settings.json
anvil/anvil.go
supersim.go

anvils start out silent but will start logging once they are ready

feat: enable logging after anvil is ready

---

anvil/anvil.go
go.mod
supersim.go
supersim_test.go

a test suite wrapper over a running instance of supersim. This makes it DRY between tests.
This wrapper will evolve as tests are added
Also introduces a dependency on stretchr/testify to write cleaner tests

supersim testsuite creator

---

anvil/anvil.go
anvil/anvil_test.go
op-simulator/op_simulator.go
supersim.go
supersim_test.go

We dont want to have to specify both the anvil & simulator ports when the anvil port is an implementation detail.
In order to simplify config, we provide the ability to start anvil on port `0`, meaning whatever is available on the host. This way we don't need to predefine this port. Since anvil is an external process, we extract the port by waiting for the `Listening on` log emitted when starting anvil.
Only apply the genesis arg to anvil if present in the config

feat: starting with port 0

---

cmd/main.go

Closes https://github.com/ethereum-optimism/supersim/issues/38
Implements a check that the machine has a minimum anvil version of 0.2.0 installed prior to starting supersim.

feat: check for minimum anvil version

---

config/chain.go
genesisdeployment/genesisdeployment.go
orchestrator/fork.go
supersim_test.go

The registry address list does not have an info about the implementation addresses which is a plus

use superchain registry AddressList as canonical type

---

anvil/anvil.go
cmd/main.go
hdaccount/hd_account_store.go
opsimulator/opsimulator.go
supersim_test.go

closes https://github.com/ethereum-optimism/supersim/issues/26
- opsim on startup starts a background task to listen for L1 deposit transactions
- simply takes a emitted deposit tx log and submits it as a Deposit transaction type on the L2
- NOTE: test will fail this needs to wait until the new foundry nightly build gets released with the fix for block.basefee override. won't merge until Jul 26th

feat(opsim): listen for deposit transactions

---

anvil/anvil.go
cmd/main.go
config/chain.go
config/cli.go
opsimulator/opsimulator.go
orchestrator/fork.go
orchestrator/orchestrator.go
orchestrator/orchestrator_test.go
supersim.go
supersim_test.go
testutils/mockchain.go

Closes ethereum-optimism/supersim#68
Binding to port `0` is useful in scenarios like CI where port conflicts are likely. The default behavior of supersim should be predictable. We add two cli flags
```
--l1.port value                     (default: 8545)                    ($SUPERSIM_L1_PORT)
Listening port for the L1 instance. `0` binds to any available port
--l2.starting.port value            (default: 9545)                    ($SUPERSIM_L2_STARTING_PORT)
Starting port to increment from for L2 chains. `0` binds each chain to any
available port
```
**Related changes**
1. Anvil.Start() must always wait for the port to be available. Otherwise the rpc can't establish a connection. We can remove `WaitUntilReady` for anvil because of this (separate pr)
2. Some code cleanup on `SourceChainID`. …

Port Configuration

---

anvil/anvil.go
bindings/l1_block_interop.go
config/chain.go
opsimulator/derive.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
supersim_test.go
testutils/mockchain.go

closes https://github.com/ethereum-optimism/supersim/issues/59
- on startup, adds all chainIDs in the dependency set to the L1BlockInterop state using deposit tx type.
- added bindings for L1BlockInterop contract - we can remove it once the monorepo has an exported binding for this

feat(opsim): setup L1BlockInterop state during startup

---

opsimulator/opsimulator.go

Updates the reverse proxy to return a `204` along with the cors headers, when the browser triggers a preflight request

Update reverse proxy to handle options requests

---

opsimulator/json.go
opsimulator/opsimulator.go
orchestrator/orchestrator_test.go
supersim_test.go

Add support to parse either batch requests or normal json rpc requests.
The jsonrpc field can either be a string or numeric value. This causes 400s when a string since the current struct hard codes it to a uint. Fix this by switching this field to a `json.RawMessage` to defer decoding. We dont care about this field anyways.

fix: opsimulator json parsing logic / feat: parse batch requests

---

README.md
anvil/anvil.go
config/chain.go
contracts/.gitignore
opsimulator/crossl2inbox.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
supersim_test.go
testutils/mockchain.go

Closes: https://github.com/ethereum-optimism/supersim/issues/19
Closes: https://github.com/ethereum-optimism/supersim/issues/18
Adds interop invariant checks to the opsimulator, and will reject transactions that do not meet the interop invariants. The interop invariant checks are in line with the interop spec: https://specs.optimism.io/interop/overview.html

feat: interop invariant checks

---

.gitignore
opsimulator/json.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
supersim_test.go

Closes: https://github.com/ethereum-optimism/supersim/issues/55
Closes: https://github.com/ethereum-optimism/supersim/issues/79
Closes: https://github.com/ethereum-optimism/supersim/issues/92
Sets up proper response handling for batch requests. Specifically, when errors are encountered during batch requests, the entire response is not errored and just the specific request gets an `Error` field set.

feat: handle batch responses

---

.github/workflows/release.yml
.gitignore
.goreleaser.yaml

context: https://github.com/ethereum-optimism/supersim/issues/66
sets up go binary build + release using goreleaser
- only way to trigger is by creating a new tag
- in the future we can figure out nightly releases / automated CI releases
to test locally, 
1. install [goreleaser](https://goreleaser.com/install/) ie. `brew install goreleaser`
2. run a release - output should be in the `dist` folder
```
goreleaser release --snapshot --clean
```

ci: setup release on new tags

---

.gitmodules
contracts/foundry.toml
contracts/src/MockL2NativeSuperchainERC20.sol
contracts/test/MockL2NativeSuperchainERC20.t.sol

context: https://github.com/ethereum-optimism/supersim/issues/89
heavily adapted from https://github.com/ethereum-optimism/optimism/pull/11256/files#diff-dcb1bb1a9a7da769141e9ae3cfe1209f666365a408ce8a2c856bc3597e65b0cd
Meant to be the most barebones implementation of the SuperchainERC20 that devs can test on supersim with.
- minted / burned natively on the L2 (no L1 bridging)
- mint / burn is permissionless, to make it easier for devs to test with
- this will be deployed to the supersim L2s at genesis, and tokens minted to the dev accounts by default
The ISuperchainERC20 and accompanying standards are constantly changing, so I'll keep this updated with the latest code in the monorepo when the event / function signatures change.

feat(contracts): MockL2NativeSuperchainERC20

---

anvil/anvil.go
config/chain.go
orchestrator/orchestrator.go
orchestrator/orchestrator_test.go
supersim.go
supersim_test.go
testutils/mockchain.go

Closes: https://github.com/ethereum-optimism/supersim/issues/102
Closes: https://github.com/ethereum-optimism/supersim/issues/100
This PR synchronizes the anvil block timestamps across all L2 nodes prior to supersim startup. This is done using the following steps:
1. start the nodes in automine mode so no new blocks are created
2. turn on 2 second interval mining for all nodes using a goroutine after all anvil nodes have marked themselves as ready using `evm_setIntervalMining`
This synchronization is not perfect but it should ensure that the clocks between anvil nodes never drift further than 2 seconds apart.

fix: sync clocks across anvil nodes on startup

---

anvil/anvil.go
config/chain.go
opsimulator/deposits.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
supersim.go
supersim_test.go
testutils/mockchain.go

Closes #107 
- Remove `EthClient` interface from `Chain`
- Make log simulation apart of the interface to simply code and remove public type arguments
- `--optimism` only if L2
- `Stopped` deadcode. Remove from orchestrator,anvil,opsim. And just return false in `Supersim`
- Remove `WaitUntilReady` as all the processes already pause until started
- Make some types internal

fixes: anvil & chain abstraction

---

anvil/anvil.go
config/chain.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
orchestrator/orchestrator_test.go
supersim_test.go
testutils/mockchain.go

In order to not leak the underlying chain type, opsim should also be a `config.Chain` when wrapping the L2 chain. This can easily be done by embedding the l2 chain in the opsim struct.
Now all references in the orchestrator and supersim can use `config.Chain` regardless if it's fronted by opsim or not
**aside**: The interface doesn't need methods for `Name()` and `ChainID()` as these are already available via the config struct

fix: opsim is follows the config.Chain abstraction

---

bindings/l2nativesuperchainerc20.go
bindings/parsedabi.go
opsimulator/opsimulator.go

closes https://github.com/ethereum-optimism/supersim/issues/82
Logs the SendERC20 and RelayERC20 event logs for the L2NativeSuperchainERC20
It's a bit noisy rn but we can do a cleanup of the logs in a separate PR

feat(opsim): log L2NativeSuperchainERC20 events

---

config/cli.go
l2tol2msg/indexer_test.go
l2tol2msg/relayer.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
orchestrator/orchestrator_test.go
supersim.go

- adds new flag `supersim --autorelay` 
- this mode automatically relays messages sent to the L2ToL2CrossDomainMessenger using this account `0xa0Ee7A142d267C1f36714E4a8F75612F20a79720`
- in the future we can make the sender configurable too
- creates an `L2ToL2MessageRelayer` that listens to send events using the `L2ToL2MessageIndexer` then sends the corresponding relayMessage tx on the destination chain
- right now the opsim proxy does not support ws connections, making unsuitable for the `L2ToL2MessageIndexer` which uses ws subscriptions. `L2ToL2MessageIndexer` directly calls the underlying chain RPC, bypassing opsim. 
- `L2ToL2MessageRelayer` sends tx through the opsim proxy, so all invariant checks should happen
- as soon as a `SentMessage` log is emitted (ie. block is mined) on the …

feat(l2tol2msg): create autorelayer mode

---

interop/indexer.go
interop/indexer_test.go
interop/message.go
interop/relayer.go
interop/store.go
interop/store_test.go
orchestrator/orchestrator.go

renamed so we can consolidate the interop features

chore: rename l2tol2msg package to interop

---

anvil/anvil.go
config/chain.go
opsimulator/json.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
supersim.go

Improve logging (spit out contract addresses). Code cleanup around this
```
Available Accounts
-----------------------
(0): 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
(1): 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
...
Private Keys
-----------------------
(0): 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
(1): 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
...
Orchestrator Config
-----------------------
L1: Name: Local  ChainID: 900  RPC: http://127.0.0.1:8545  LogPath: /var/folders/y6/bkjdghqx1sn_3ypk1n0zy3040000gn/T/anvil-chain-900-4142322133
L2s: Predeploy Contracts Spec ( https://specs.optimism.io/protocol/predeploys.html )
* Name: OPChainA  ChainID: 901  RPC: http://127.0.0.1:9545  LogPath: …
```

chore: supersim changes from demo

---

README.md

README is getting way too verbose for a quick start.
Will split out most of the content into a separate docs site in [this PR](https://github.com/ethereum-optimism/supersim/pull/138). As a result, shortened the README and made it focus on getting devs started quickly.

docs: shorten README.md

---

contracts/script/DeployCrossChainPingPong.s.sol
contracts/src/CrossChainPingPong.sol
contracts/test/CrossChainPingPong.t.sol

an example contract that wraps L2CDM to use in guides.
contract is deployed on multiple chains, and allows hitting the "ball" back and forth between the chains using the L2CDM

example: add CrossChainPingPong.sol

---

.github/workflows/release.yml
.goreleaser.yaml

Pushes new releases as formulas to https://github.com/ethereum-optimism/homebrew-tap

ci: setup homebrew releases

---

anvil/anvil.go
config/chain.go
config/cli.go
orchestrator/orchestrator_test.go
supersim.go

closes https://github.com/ethereum-optimism/supersim/issues/132
- deletes temp files for
- logs
- genesis.json: the genesis.json files can get very large and fill up disk space
- `--logs.directory` allows specifying log directory - if specified it won't be deleted by default

fix: remove temp file on shutdown, allow specifying log dir

---

config/chain.go

fix bug introduced in https://github.com/ethereum-optimism/supersim/pull/172 re: the formatting of printed private keys

fix: default dev account printing

---

go.mod
go.sum

The Superchain Registry module is updated to the latest version to be able to use newly added chains to it with `supersim 
fork` mode.
One example of currently unsupported chain is Lisk, which was added to the Superchain Registry on [September 19th](https://github.com/ethereum-optimism/superchain-registry/pull/502).

Update Superchain Registry module to the latest version

---

cmd/main.go

1. create a git tag (semver)
2. push a git tag
3. goreleaser passes the version / tag info in the build process, and the CLI should have the correct version
related: https://github.com/ethereum-optimism/supersim/issues/192
^ will test out the release flow before closing

feat(cli): include ldflag version in --version command

---

genesis/cmd/main.go
go.mod
go.sum
interop/applier.go
opsimulator/opsimulator.go

Part of https://github.com/ethereum-optimism/supersim/issues/200
Closes https://github.com/ethereum-optimism/supersim/issues/198

feat: add `SuperchainTokenBridge` to interop applier

---

.github/actions/setup/action.yml

I noticed that `golangci-lint` is [failing to install ](https://github.com/ethereum-optimism/supersim/actions/runs/11408059484/job/31745440552#step:3:38) on a couple of PRs now when we're pulling in go `1.23` so this PR just pins to the go version in our go.mod file to avoid this. We'll most likely need to bump our `golangci-lint` version once we want to update our go version

CI pins go version to whats in go.mod

---

go.mod
go.sum
interop/indexer.go
opsimulator/opsimulator.go
supersim_test.go

`ethClient.getBlockByNumber` (source: [here](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbynumber)) by default passes "true" to "transaction_detail_flag", which causes it to return an array of tx when fetching the block.
Anvil returns a block like below. Notice how there's no tx type in the transaction object, which is a deposit tx. 
1. since the tx type is missing
2. geth library assumes it's a legacy tx
3. attempts to unmarshal the tx object
4. throws error because it can't find `gasPrice`, which is a required param.
this only happens occasionally in tests IFF the send message happens in same block as the deposit tx that sets the dependency set.
```
{
"hash": "0xdb27f4591ceaad75452baece037724d6fb3c915e64c1ce27862381a27b337a44",
"parentHash": …
```

fix(test): fix issue causing required field 'gasPrice' in transaction

---

go.mod
go.sum
orchestrator/orchestrator.go
readme_test.go
supersim_test.go
testutils/wait.go

- remove `time.sleep` in favor of `wait.for`
- fix bug with startup in fork mode
- parallelizes supersim_test since those don't should not clash with each other (they use different ports)
- currently this tests from 4m 20s => 2m
- if this causes flake will remove later

fix(test): remove time.sleep and improve test suite startup time

---

admin/admin.go
admin/admin_test.go
config/cli.go
orchestrator/orchestrator.go
supersim.go

Admin port needs to be configurable. Fixes CI flakes. The cli flag default can be 8420
- Leave the orchestrator package to detail with chain orchestration and the supersim struct holding reference to the admin server

fix(adminSrv): configurable port

---

admin/admin.go
admin/admin_test.go
supersim.go

added getL1Addresses(chainId) support with /getL1Addresses/:chainID, essentially letting devs check L1 address for a particular L2 chain via chain ID
**Additional context**
Just prints L1 address for particular L2 chain via chain ID
**Metadata**
- adds extra functionality requested in #204

feat(admin): added getL1Addresses(chainId) rpc support 

---

config/chain.go
config/cli.go
docs/src/reference/supersim-fork.md
docs/src/reference/supersim.md
interop/indexer.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
supersim.go
supersim_test.go

- by default the inclusiondelay is false 
- adds --interop.inclusiondelay flag in cli which delays sent messages by 5 seconds
Todo:
**Metadata**
#133

✨ Adds interop delay option

---

admin/admin.go
admin/admin_test.go
interop/indexer.go
orchestrator/orchestrator.go
orchestrator/orchestrator_test.go
supersim.go
supersim_test.go

added getL2ToL2 Message(msgHash), essentially letting devs fetch L2ToL2Message via msgHash
**Metadata**
- adds extra functionality requested in #204

feat(admin): added rpc method for getL2ToL2 Message(msgHash)

---

docs/src/guides/deposit-transactions.md

1. The word "**the**" is repeated.  
**Corrected Sentence:** "This implies the execution engine used with Supersim must support the optimism [[Deposit Transaction Type](https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type)](https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type)."
2. "**exeuction**" is misspelled.  
**Corrected Sentence:** "This implies the execution engine used with Supersim must support the optimism [[Deposit Transaction Type](https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type)](https://specs.optimism.io/protocol/deposits.html#the-deposited-transaction-type)."
**Thanks for Supersim!**

docs: fix typos Update deposit-transactions.md

---

anvil/anvil.go
config/chain.go
config/cli.go
docs/src/reference/supersim-fork.md
docs/src/reference/supersim.md
orchestrator/fork.go
orchestrator/orchestrator.go
orchestrator/orchestrator_test.go
supersim.go

This PR introduces a new cli flag `--odyssey.enabled`. It adds support to start both the L1 & L2 anvil instances with [odyssey features enabled](https://book.getfoundry.sh/reference/cli/anvil?highlight=odyssey#anvil) allowing developers to start testing out more experimental features multichain

Adds odyssey support

---

contracts/foundry.toml
contracts/script/predictionmarket/Deploy.s.sol
contracts/script/tictactoe/Deploy.s.sol
contracts/src/predictionmarket/MarketResolver.sol
contracts/src/predictionmarket/PredictionMarket.sol
contracts/src/predictionmarket/factories/BlockHashMarketFactory.sol
contracts/src/predictionmarket/factories/MockResolverFactory.sol
contracts/src/predictionmarket/factories/TicTacToeMarketFactory.sol
contracts/src/predictionmarket/resolvers/BlockHashResolver.sol
contracts/src/predictionmarket/resolvers/MockResolver.sol
contracts/src/predictionmarket/resolvers/TicTacToeResolver.sol
contracts/src/predictionmarket/utils/BlockHashEmitter.sol
contracts/src/predictionmarket/utils/MintableBurnableERC20.sol
contracts/test/pingpong/CrossChainPingPong.t.sol
contracts/test/predictionmarket/PredictionMarket.t.sol
contracts/test/tictactoe/TicTacToe.t.sol
docs/src/SUMMARY.md
docs/src/examples/cross-chain-tictactoe.md
docs/src/guides/interop/cross-chain-event-composability-predictionmarket.md
docs/src/guides/interop/cross-chain-event-reads-tictactoe.md

contracts for the prediction market example app
- Create a prediction market on the outcome of a tictactoe game
- Create a prediction market on the even/odd result of a block hash
Features not supported in the prediction market:
- Selling a position back into the market
- Incentivizing the first better (negative EV for them).

prediction market contracts

---

.circleci/config.yml
.goreleaser.yaml

Continuing the migration from GHA to CircleCI, the release flow is next.
- Added the `release` workflow that runs on tag push
- There is a small existing issue where a tag referring to a commit that's not on `main` will still trigger this pipeline. Will be addressed in a separate PR since it's not a regression
- Updated version of the base image since the python version in `v0.35.0` was causing issues with `utils/get-github-access-token` command (see [here](https://app.circleci.com/pipelines/github/ethereum-optimism/supersim/42/workflows/4c7b30d4-7223-44b4-91bb-883de9681881/jobs/160))
- Removed the `install-foundry` command since the new image contains a compatible `foundry` version already
- Removed the `TAP_REPO_GITHUB_TOKEN` environment variable from `.goreleaser.yaml`. …

chore: Release flow migration to CircleCI [2/N]

---

.circleci/config.yml
Justfile
README.md
mise.book.toml
mise.toml

Before moving on to the GitHub Pages publishing workflow, I added `mise` as a dependency manager. `mise` is being used in the [`optimism` monorepo](https://github.com/ethereum-optimism/optimism/blob/develop/mise.toml) and provides a great way of managing tooling required for development.
It is an add-on, it does not break or affect any existing development flows, just provides a convenient way of setting up your development environment (as well as the CI environment).
To further optimize the CI runs, dependencies that are only required for book/docs building have been pulled out into a separate `mise.book.toml` file. See [configuration environments documentation](https://mise.jdx.dev/configuration/environments.html) for more information.
`mise` then allows us to use the …

chore: Manage dependencies using mise [3/N]

---

.circleci/config.yml

**This PR builds on top of #319 and can be reviewed once that one is merged.**
Migrates the `deploy-docs.yaml` github workflow to CircleCI. To tigthen the security, the workflow is split into two jobs:
- `book-build` does not have access to any credentials and is only responsible for building the github pages artifacts
- `book-publish` receives the build artifacts and pushes them to github pages
`ethereum-optimism/circleci-utils` orb version was bumped to `0.0.13` since `0.0.12` had a small issue with publishing github pages.
**Tests**
No-op publish has been tested [here](https://app.circleci.com/pipelines/github/ethereum-optimism/supersim/114/workflows/e03578c5-10ab-4fdc-9004-49f9d2124524/jobs/486). Dummy change in a book has been tested …

chore: Migrate Github Pages publishing to CircleCI [4/N]

---

anvil/anvil.go
config/chain.go
interop/relayer.go
interop/store.go
orchestrator/orchestrator.go
testutils/mockchain.go

Updates the auto-relayer to handle messages that are dependent on one another. This is done by looking for messages that when relayed would revert with the `DependentMessageNotSuccessful(bytes32 msgHash)` error signature. If this revert is encountered, then the relayer will wait to relay this message until the msgHash that it depends on is successfully relayed.

feat: update auto-relayer to handle dependent message hashes

---

cmd/main.go

will update on next stable release. Otherwise we're forcing people to use nightly builds

fix: revert minimum anvil version

---

docs/src/chain-environment/contracts/README.md

The contract files are not built into the docs static site so we need a direct link to them instead of a relative link.

fix(docs): use direct link instead of relative link

---

contracts/script/DeployL2PeripheryContracts.s.sol
genesis/generated/900-l1-genesis.json

more context: https://github.com/ethereum-optimism/supersim/pull/347#issuecomment-2676472821
applying hacky temp fix to give the gas estimator default address 0x000...000 more wei than the number of chains.

tempfix: eth_call fails with insufficient gas

---

anvil/anvil.go
config/chain.go
orchestrator/fork.go
orchestrator/orchestrator.go
testutils/mockchain.go

closes https://github.com/ethereum-optimism/supersim/issues/305
- previously both L1 and L2 chains had a hardcoded block time of 2s
- fork mode also assumed this to calculate l2 block height based on the l1 block height
- default block time for L1 is 12s
- default block time for L2s is 2s
- when forking, it reads block time from the superchain registry (ie. unichain should be 1s) for both 1. inferring l2 block height from l1, 2. the mining speed on the forked chain

feat: vary block time for chain

---

anvil/anvil.go
config/chain.go
opsimulator/opsimulator.go
orchestrator/orchestrator.go
supersim_test.go
testutils/mockchain.go

Closes https://github.com/ethereum-optimism/supersim/issues/374
Another approach to websocket support. This involves propagating the websocket connection to the underlying anvil instance for eth subscription requests.

Enable websocket support on l2 chains - propagating ws connection to anvil approach
